[server]
address = "example.com:4000"

[user]
user = "user"
password = "password"

[algorithm]
heuristic_cut = 1.2
heuristic_decline_cut = 1.5
heuristic_decline_length = 5
koeff_goal_distance = 0.5
koeff_space = 0.5
koeff_center_line_offset = 0.1
# ratio of playground width
invert_at_first_steps = 0.1
